# Generated by Django 3.0.8 on 2020-08-12 15:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('About', models.CharField(max_length=200)),
                ('Image', models.ImageField(blank=True, null=True, upload_to='Answer')),
                ('thumbsup', models.IntegerField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('About', models.CharField(max_length=200)),
                ('Image', models.ImageField(blank=True, null=True, upload_to='Question')),
                ('Primary_answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainpage.Answer')),
            ],
        ),
        migrations.CreateModel(
            name='comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('About', models.CharField(max_length=200)),
                ('Image', models.ImageField(blank=True, null=True, upload_to='comment')),
                ('Question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainpage.Question')),
            ],
        ),
    ]
