# Generated by Django 3.0.8 on 2020-08-12 15:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0002_auto_20200812_2120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='Primary_answer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainpage.Answer'),
        ),
    ]
