# Generated by Django 3.0.8 on 2020-08-20 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0003_auto_20200812_2122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='thumbsup',
            field=models.IntegerField(),
        ),
    ]
